
bookiesports_chain: hercules
subscriptions:
    mask_providers: 'maryhadalittlelamb'
    witnesses:
        - url: http://ec2-35-183-16-213.ca-central-1.compute.amazonaws.com:8010/trigger
          group: herculeschain

providers:
    some_provider_name: 
        user: carrot
        password: mypassword